CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    LOGIN VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    BIRTHDAY DATE NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS FRIENDS (
    REQUEST INTEGER NOT NULL,
    RESPONCE INTEGER NOT NULL,
    STATUS INTEGER NOT NULL,
    PRIMARY KEY(REQUEST, RESPONCE)
);

CREATE TABLE IF NOT EXISTS FRIENDS_STATUS (
    ID INTEGER NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS FILMS (
    ID INTEGER NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    DURATION INTERVAL SECOND(18),
    RATING INTEGER NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS FILM_GENRES (
    FILM_ID INTEGER NOT NULL,
    GENRE_ID INTEGER NOT NULL,
    PRIMARY KEY(FILM_ID, GENRE_ID)
);

CREATE TABLE IF NOT EXISTS GENRES (
    ID INTEGER NOT NULL,
    GENRE VARCHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS RATINGS (
    ID INTEGER NOT NULL,
    RATING VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS LIKES (
    USER_ID INTEGER NOT NULL,
    FILM_ID INTEGER NOT NULL,
    PRIMARY KEY(USER_ID, FILM_ID)
)